name: IPTV Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: 获取代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 运行 Python
        run: |
          python --version
          echo "IPTV 自动更新系统已启动"
